const mongoose = require('mongoose');

const mcqSchema = new mongoose.Schema(
  {
    fileId: {
      type: String,
      required: true,
      index: true
    },
    segmentId: {
      type: String,
      required: true,
      index: true
    },
    question: {
      type: String,
      required: true
    },
    options: {
      type: [String],
      required: true,
      validate: {
        validator: function(v) {
          return Array.isArray(v) && v.length >= 2;
        },
        message: 'MCQ must have at least two options'
      }
    },
    correct: {
      type: Number,
      required: true,
      validate: {
        validator: function(v) {
          return v >= 0 && v < this.options.length;
        },
        message: 'Correct answer index must be valid'
      }
    },
    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'medium'
    },
    isAutoGenerated: {
      type: Boolean,
      default: true
    },
    metadata: {
      type: Object,
      default: {}
    }
  },
  {
    timestamps: true
  }
);

// Compound index for faster lookups
mcqSchema.index({ fileId: 1, segmentId: 1 });

module.exports = mongoose.model('MCQ', mcqSchema);
